[pytest]
testpaths = tests
filterwarnings =
    ignore:ast\.Str is deprecated and will be removed in Python 3\.14; use ast\.Constant instead:DeprecationWarning
    ignore:Constant\.__init__ got an unexpected keyword argument 's'\. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3\.15\.:DeprecationWarning
    ignore:Attribute s is deprecated and will be removed in Python 3\.14; use value instead:DeprecationWarning
    ignore:Constant\.__init__ missing 1 required positional argument.*:DeprecationWarning
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version\..*:DeprecationWarning